### ISSUE TITLE
cant load de conferences

### ISSUE THREAD

**Issue by jgarcia92** [lemberg/connfa-webapp#5]
![imagen](https://user-images.githubusercontent.com/8104235/38168623-dd227e68-350e-11e8-8c42-e1729c5a091a.png)

connfa-integration-server and conffa webapp are running in localhost(my laptop) i dont know  if some issue of api url set in .env?

**Comment by aht61** [comment]
After a few hours of trial and error, I have noticed that a slash "/" was missing in config.ts file!
Remember to add the closing "/" in the following line before building your web app:

export const CONFIG = {
...
    production: {
        "apiUrl": "{your_production_servers_domain}/api/v2/{event_alias}/",
        "googleApiKey": "Your Goggle Map Key",
    }
};

Hope this helps.
