### ISSUE TITLE
Gulp-util dependency is breaking gulp build

### ISSUE THREAD

**Issue by mateuswetah** [lemberg/connfa-webapp#6]
Hi there, I am not able to put this up :(

When I run `gulp build`,I get the following output:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/gulp/bin/gulp.js:4:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I already followed procedures as in [this link](https://stackoverflow.com/questions/21406738/cant-get-gulp-to-run-cannot-find-module-gulp-util) with no success.

This kind of dependency seems to break a lot of projects, I see people moving into Docker to have ready environments for that.

BTW, is this project still active? I see so much potential on it and really would like to use it (or any similar solution) for a local conference in my country, but it seems that it's a bit off...

Thanks in any case for all the effort!

**Comment by yuriymyrosh** [comment]
Hi @mateuswetah, can you try to reinstall gulp on your machine running:
```
npm remove -g gulp
npm install -g gulp
```
or remove `node_modules` folder and then reinstall them using `npm install`

Yes, project is still active, but currently it is in beta

**Comment by mateuswetah** [comment]
Hey hey hey, good to know you guys are here! 

Thanks for the tip, it was a really dumb thing,  tried it before but only with `gulp-util` instead of `gulp`. Now it builds. I'll keep following install instructions so. Hope to one day be able to contribute here o/
